### ISSUE TITLE
App won't let me join room if url includes https

### ISSUE THREAD

**Issue by rgustavsson** [daily-demos/daily-android-demo#2]
In the demo app, when I include the scheme (https) in the url, the join button is disabled.
If I remove the scheme and hit the enabled join button, I get "failed to connect".
If I debug the application and manually add the https scheme to the url variable, then I can connect.

**Comment by filipi87** [comment]
Hi @rgustavsson , could you share what Is the URL (just change your domain for something else) that you are using so I can try to simulate the issue here ? 
The pattern is like this:
**_https://yourdomain.daily.co/yourroom_**

This way, in our internal tests, the button join is always enabled. So It would be important to have more details so we can reproduce the issue.

**Comment by rgustavsson** [comment]
Closing this!
I probably did something wrong. I didnt re-test in this demo project but when I had copied parts of your demo code to my own test app it worked fine, so maybe a typo. Sorry for wasting your time!
